/**
 * POST /api/chat/start
 *
 * Open a new chat conversation for a storefront visitor.
 *
 * Public endpoint (no auth — visitors aren't logged in). Rate-limited per IP.
 *
 * Body:
 *   {
 *     dealerSlug: string;       // storefront slug, e.g. "mahon-motors"
 *     anonymousId: string;      // UUID generated by the widget (localStorage)
 *     locale?: "en" | "es";     // explicit choice from widget toggle
 *     vehicleId?: string;       // if visitor is on a VDP
 *     listingId?: string;       // if visitor is on a service/home detail
 *     referer?: string;
 *   }
 *
 * Response:
 *   {
 *     conversationToken: string;  // opaque, used for /api/chat/message
 *     greeting: string;           // assistant's opening message
 *     locale: "en" | "es";
 *   }
 */

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { randomBytes, createHash } from "node:crypto";
import { encryptLeadField } from "@/lib/leadCrypto";
import { durableRateLimit } from "@/lib/rateLimit";

export const dynamic = "force-dynamic";

function hashIp(ip: string, dealerId: string): string {
  return createHash("sha256").update(`${ip}:${dealerId}`).digest("hex");
}

function getClientIp(request: NextRequest): string {
  return (
    request.headers.get("x-vercel-forwarded-for") ||
    request.headers.get("x-forwarded-for")?.split(",")[0].trim() ||
    request.headers.get("x-real-ip") ||
    "unknown"
  );
}

function negotiateLocale(
  request: NextRequest,
  explicit: string | undefined,
  dealerDefault: string,
  refererPath: string | null
): "en" | "es" {
  // 1. Explicit widget toggle wins
  if (explicit === "es" || explicit === "en") return explicit;
  // 2. Dealer's hardcoded default
  if (dealerDefault === "es" || dealerDefault === "en") return dealerDefault;
  // 3. Storefront path (referer contains /es/...)
  if (refererPath && /\/es(\/|$)/.test(refererPath)) return "es";
  // 4. Accept-Language header
  const al = request.headers.get("accept-language") ?? "";
  if (/^es\b/i.test(al) || /,\s*es\b/i.test(al)) return "es";
  return "en";
}

function buildGreeting(
  locale: "en" | "es",
  dealerName: string,
  vehicleLabel: string | null,
  listingLabel: string | null
): string {
  const context = vehicleLabel || listingLabel;
  if (locale === "es") {
    if (context) {
      return `¡Hola! Soy el asistente virtual de ${dealerName}. Veo que estás mirando ${context}. ¿En qué te puedo ayudar? Para empezar, ¿cómo te llamas?`;
    }
    return `¡Hola! Soy el asistente virtual de ${dealerName}. ¿En qué te puedo ayudar hoy? ¿Cómo te llamas?`;
  }
  if (context) {
    return `Hi! I'm ${dealerName}'s AI assistant. I see you're checking out ${context}. How can I help? To start, what's your name?`;
  }
  return `Hi! I'm ${dealerName}'s AI assistant. How can I help you today? What's a good name to put you down for?`;
}

export async function POST(request: NextRequest) {
  // Rate-limit per IP — discourages bots from creating endless conversations.
  const ip = getClientIp(request);
  const rl = await durableRateLimit(`chat_start:${ip}`, 10, 60_000);
  if (!rl.allowed) {
    return NextResponse.json(
      { error: "rate_limited" },
      { status: 429, headers: { "Retry-After": String(Math.ceil(rl.retryAfterMs / 1000)) } }
    );
  }

  let body: {
    dealerSlug?: unknown;
    anonymousId?: unknown;
    locale?: unknown;
    vehicleId?: unknown;
    listingId?: unknown;
    referer?: unknown;
  };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "invalid_json" }, { status: 400 });
  }

  const dealerSlug = typeof body.dealerSlug === "string" ? body.dealerSlug : "";
  if (!dealerSlug) {
    return NextResponse.json({ error: "missing_dealer_slug" }, { status: 400 });
  }

  const anonymousId =
    typeof body.anonymousId === "string" && body.anonymousId.length >= 8
      ? body.anonymousId.slice(0, 64)
      : null;

  const dealer = await prisma.dealer.findUnique({
    where: { slug: dealerSlug },
    select: {
      id: true,
      name: true,
      slug: true,
      aiChatEnabled: true,
      aiChatDefaultLocale: true,
      ctaPreference: true,
      deletedAt: true,
      active: true,
    },
  });

  if (!dealer || dealer.deletedAt || !dealer.active) {
    return NextResponse.json({ error: "dealer_not_found" }, { status: 404 });
  }

  // Even when the dealer hasn't toggled AI chat on, allow it if they
  // explicitly chose ctaPreference=ai_chat (the toggle is just a softer
  // global switch). The storefront only renders the widget when one of
  // these is true anyway — this is defense in depth.
  if (!dealer.aiChatEnabled && dealer.ctaPreference !== "ai_chat") {
    return NextResponse.json(
      { error: "ai_chat_disabled" },
      { status: 403 }
    );
  }

  // Resolve vehicle/listing context (if provided + belongs to this dealer).
  let vehicleId: string | null = null;
  let listingId: string | null = null;
  let vehicleLabel: string | null = null;
  let listingLabel: string | null = null;

  if (typeof body.vehicleId === "string" && body.vehicleId.length > 0) {
    const v = await prisma.vehicle.findFirst({
      where: { id: body.vehicleId, dealerId: dealer.id },
      select: { id: true, year: true, make: true, model: true },
    });
    if (v) {
      vehicleId = v.id;
      vehicleLabel = [v.year, v.make, v.model].filter(Boolean).join(" ") || null;
    }
  }
  if (typeof body.listingId === "string" && body.listingId.length > 0) {
    const l = await prisma.listing.findFirst({
      where: { id: body.listingId, dealerId: dealer.id },
      select: { id: true, title: true },
    });
    if (l) {
      listingId = l.id;
      listingLabel = l.title;
    }
  }

  const refererStr =
    typeof body.referer === "string" ? body.referer.slice(0, 500) : null;

  const locale = negotiateLocale(
    request,
    typeof body.locale === "string" ? body.locale : undefined,
    dealer.aiChatDefaultLocale,
    refererStr
  );

  const conversationToken = randomBytes(24).toString("base64url");
  const conv = await prisma.chatConversation.create({
    data: {
      dealerId: dealer.id,
      vehicleId,
      listingId,
      anonymousId,
      conversationToken,
      locale,
      status: "active",
      visitorIpHash: ip !== "unknown" ? hashIp(ip, dealer.id) : null,
      visitorUserAgent:
        request.headers.get("user-agent")?.slice(0, 500) ?? null,
      visitorReferer: refererStr,
    },
    select: { id: true },
  });

  const greeting = buildGreeting(
    locale,
    dealer.name,
    vehicleLabel,
    listingLabel
  );

  // Persist the assistant's opening greeting so it's in history for the
  // next agent turn and shows up in the dashboard transcript.
  await prisma.chatMessage.create({
    data: {
      conversationId: conv.id,
      role: "assistant",
      body: encryptLeadField(greeting),
    },
  });

  return NextResponse.json({
    conversationToken,
    greeting,
    locale,
  });
}
